name: Build

on:
  push:
    branches-ignore:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine environment
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=qa" >> $GITHUB_ENV
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::632757408528:role/GitHubActionsRole
          aws-region: us-east-2

      - name: Get CodeArtifact token
        run: |
          echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain roadreadysafety \
            --domain-owner 632757408528 \
            --region us-east-2 \
            --query authorizationToken \
            --output text)" >> $GITHUB_ENV

      - run: make ci
        env:
          GIT_SHA: ${{ github.sha }}
